spring:
  datasource:
    url: jdbc:h2:mem:ezgg
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true

  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
  sql:
    init:
      mode: never

  elasticsearch:
    uris: http://localhost:9200
    username:
    password:
    connection-timeout: 5s
    socket-timeout: 10s

logging:
  level:
    org.springframework.security: DEBUG

jwt:
  secret: ${SECRET_KEY}

es:
  httpHost: "localhost"

redis:
  host: "localhost"

api:
  key: ${RIOT_API_KEY}
